#!/usr/bin/env python3

# Convert a flatform binary to a C header as shellcode 
import sys, os, binascii

if len(sys.argv) < 3:
	print("USAGE: to_c.py input.bin output.h")
	exit(1)

bin_data = None 

with open(sys.argv[1], 'rb') as fs:
	bin_data = fs.read()

hexstring = binascii.hexlify(bin_data).decode('UTF-8')

array = []

idx = 0 
while idx <= len(hexstring)-2:
	array.append(hexstring[idx:idx+2])
	idx += 2

with open(sys.argv[2], 'w') as fs:
	fs.write("\n\n/* AUTOGENERATED SHELLCODE DO NOT EDIT */\n\nuint8_t shellcode[] = {\n")
	for x in array:
		fs.write("\t0x" + str(x) + ",\n")
	fs.write("};\n\n")